server:
  port: 8082
spring:
  application:
    name: leyou-upload

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期


#swagger配置
swagger:
  enabled: true
  base-package: com.leyou.upload
  title: upload
  version: 1.0
  description: upload
  contact:
    name: leyou-upload




fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.56.101:22122