server:
  port: 9090
spring:
  application:
    name: leyou-zuul
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:9010/eureka
  instance:
    prefer-ip-address: true
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径


#ribbbon设置 负载均衡 默认采用轮询方式
ribbon:
  readTimeout: 60000
  connectTimeOut: 30000



#设置线程服务降级和熔断时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 180000

